server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://192.168.0.69:3306/dmp?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: false
  kafka:
    bootstrap-servers: 192.168.0.69:9092
  application:
    name: dmp
  redis:
    host: 192.168.0.69
    port: 6379
    timeout: 3000
    pool:
      max-idle: 20
      min-idle: 5
      max-active: 20
      max-wait: 1000


#cache configuration
#unit second
cache:
  expireTime: 1800



eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1001/eureka/
#多网卡需要把这配置开了
  instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1

#REST超时配置
rest:
  ReadTimeout: 30000
  ConnectTimeout: 3000


# LoRa server
lora:
  enable: false
  userName: admin
  password: admin
  login: https://10.10.107.242:8080/api/internal/login
  createGateway: https://10.10.107.242:8080/api/gateways
  createDevice: https://10.10.107.242:8080/api/devices
  networkServerID: 1
  organizationID: 1
  channelConfigurationID: 1
  applicationID: 1
  deviceProfileID: 3df1b9e9-f304-459c-8f2f-1dd3dca36c76

max:
  allow:
    export:
      num: 50000

#upgrade task
upgrade:
  path: D://updateFile//
  host: 127.0.0.1


kafka:
  attributeTopic: device.controllcommand.down

hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000

idGenerator:
  workId: 1
  dataId: 1
