eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1001/eureka/
    instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1

server:
  port: 8001
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
      config:
        server:
          git:
            uri:https://github.com/qiushuijun/test/
            search-paths:config-repo
            username:qiushuijun
            password:qsj13824826365
    bus:
      trace:
        enabled: true
    stream:
      #指定用kafka stream来作为默认消息中间件
      default-binder: kafka
      kafka:
        #来自KafkaBinderConfigurationProperties
        binder:
          brokers: 192.168.0.69:9092
          zkNodes: 192.168.0.69:2181